<a href="https://colab.research.google.com/github/SantiagoRodriguez8881/Metodos1_JuanPabloMartinez_SantiagoRodriguez/blob/La-ramita-del-snat/Puntos_2_4_8_algebra_lineal.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import math
import sympy as sym
import matplotlib.pyplot as plt

# Ejercicio 2 :

# Definamos nuestro sistema:
A = np.array([[3.,-1.,-1.],[-1.,3.,1.],[2.,1.,4.]])
b = np.array([1.,3.,7.])


def Gauss_seidel(A,b,x,tol = 1e-16,Nm = 1000):
  x = x.copy()
  for it in range(Nm):
    x1 = np.copy(x)
    Suma = 0.
    for i in range(A.shape[0]):
      Suma = 0.
      for j in range(A.shape[1]):
        if i != j:
          Suma += A[i,j]*x[j]

          x1[i] = (b[i] - Suma)/A[i,i] # Actualizamos la variable para acercarnos a la solucion mas rapido
    # Criterio de convergencia
    if np.linalg.norm( np.dot(A,x1)-b) < tol:
      break

    x = np.copy(x1)
  return x, it

x0 = np.array([0.,0.,0.])

Gauss_seidel(A,b,x0)

(array([1., 1., 1.]), 34)

In [2]:
# Ejercicio 4:

def Multiplicador(A,B):
  # Nueva matriz

  C = np.zeros((A.shape[0],B.shape[1]))
  if A.shape[1] != B.shape[0]:
    return "Las matrices no son compatibles"
  else:
    for i in range(A.shape[1]):
      for j in range(B.shape[0]):

        # Producto interno
        C[i,j] = np.dot(A[i,:],B[:,j])
  return C

# Vamos a probar nuestro algoritmo

# Definamos nuestras matrices:
A1 = np.array([[1.,0.,0.],[5.,1.,0.],[-2.,3.,1.]])
B1 = np.array([[4.,-2.,1.],[0.,3.,7.],[0.,0.,-2.]])


AA = Multiplicador(A1,B1)
Multiplicador(A1,B1)
# Funciona :D

array([[ 4., -2.,  1.],
       [20., -7., 12.],
       [-8., 13., 17.]])

In [3]:
# Ejercicio 8:

# Descomposicion LU

def Descomp(AA):
  A = AA.copy()
  U = A
  L = np.zeros_like(A)
  for i in range(A.shape[0]):
    L[i,i] = 1
  for i in range(len(A[0])):

    for j in range(i+1,len(A[0])): # Vamos a encontrar las matrices U y L

      a = A[j,i]/A[i,i]
      L[j,i] = a
      U[j,:] -= a*A[i,:]
  return L,U
Descomp(AA)


(array([[ 1.,  0.,  0.],
        [ 5.,  1.,  0.],
        [-2.,  3.,  1.]]),
 array([[ 4., -2.,  1.],
        [ 0.,  3.,  7.],
        [ 0.,  0., -2.]]))