In [26]:
import matplotlib.pyplot as plt
import numpy as np
import sympy as sym
import math 
from scipy.special import laguerre

In [27]:
Raices_Laguerre = {}
x = sym.Symbol("x", real=True)
X = np.linspace(0,100,10000)

def Laguerre(x,n):
    exp_factorial = sym.exp(x)/math.factorial(n)
    funcion_para_derivar = (x**n)*sym.exp(-x)
    return exp_factorial*sym.diff(funcion_para_derivar,x,n)

def DerivadaCentral(f,x,h=1e-5):
    return (f(x+h)-f(x-h))/(2*h)

def NewtonRaphson(f, xn, i_max = 1000, tolerancia=1e-6):
    error = 1
    i = 0
    xn1 = xn
    while error > tolerancia and i < i_max:
        try:
            xn1 = xn - f(xn)/DerivadaCentral(f,xn)
            error = np.abs(f(xn)/DerivadaCentral(f,xn))
        except ZeroDivisionError:
            return None
        xn = xn1
        i += 1
    if i == i_max:
        return False
    else:
        return xn

def GetAllRoots(f, x, tolerancia = 4):
    Roots = np.array([])
    for i in x:
        possible_root = NewtonRaphson(f,i)

        if possible_root != False:
            root = round(possible_root, tolerancia)
            if root not in Roots:
                Roots = np.append(Roots, root)

    Roots.sort()
    return Roots

for i in range(1,6):
    Poly_Laguerre_Sym = Laguerre(x,i)
    Poly_Laguerre = sym.lambdify([x], Poly_Laguerre_Sym,"numpy")
    Raices = GetAllRoots(Poly_Laguerre, X)
    Raices_Laguerre[f"Raices de del polinomio {i} de Laguerre"] = Raices.tolist()
Raices_Laguerre



{'Raices de del polinomio 1 de Laguerre': [1.0],
 'Raices de del polinomio 2 de Laguerre': [0.5858, 3.4142],
 'Raices de del polinomio 3 de Laguerre': [0.4158, 2.2943, 6.2899],
 'Raices de del polinomio 4 de Laguerre': [0.3225, 1.7458, 4.5366, 9.3951],
 'Raices de del polinomio 5 de Laguerre': [0.2636,
  1.4134,
  3.5964,
  7.0858,
  12.6408]}

In [28]:
#Para comparar (Código hecho con chatgpt)
def laguerre_roots(n):
    # Genera los coeficientes del polinomio de Laguerre
    coef = laguerre(n, monic=True)
    # Encuentra las raíces del polinomio
    roots = np.roots(coef)
    return roots

for n in range(1, 6):
    roots = laguerre_roots(n)
    print(f"Raíces del polinomio L_{n}(x):")
    print(np.round(roots, 4))
    print()

Raíces del polinomio L_1(x):
[1.]

Raíces del polinomio L_2(x):
[3.4142 0.5858]

Raíces del polinomio L_3(x):
[6.2899 2.2943 0.4158]

Raíces del polinomio L_4(x):
[9.3951 4.5366 1.7458 0.3225]

Raíces del polinomio L_5(x):
[12.6408  7.0858  3.5964  1.4134  0.2636]

